# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Rivka Template App"
client_id = "7ab60da68715cfe1ada32e8ccdf37ccc"
application_url = "https://outputs-toshiba-monaco-inclusion.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://outputs-toshiba-monaco-inclusion.trycloudflare.com/auth/callback",
  "https://outputs-toshiba-monaco-inclusion.trycloudflare.com/auth/shopify/callback",
  "https://outputs-toshiba-monaco-inclusion.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "newbie-dkcx.myshopify.com"
